### PR TITLE
switch to ginkgo v2

### PR DESCRIPTION
**Pull request by phil9909**
Thank you for submitting a pull request to the bytefmt repository!

We appreciate the contribution. To help us understand the context for your pull request, please fill out this template to the best of your ability.

## Please make sure to complete all of the following steps

1. Check the [Contributing document](https://github.com/cloudfoundry/diego-release/blob/develop/CONTRIBUTING.md) on how to sign the CLA and run tests.
1. Submit your PR to this repo.
1. [**Submit an accompanying PR Review Request**](https://github.com/cloudfoundry/diego-release/issues/new?assignees=&labels=&template=pr-review-request.md&title=%5BBYTEFMT+PR+REVIEW%5D%3A) referencing this PR so the Diego Team knows to review your pull request.
* **Note: this PR will not be reviewed unless you submit the [PR Review Request](https://github.com/cloudfoundry/diego-release/issues/new?assignees=&labels=&template=pr-review-request.md&title=%5BBYTEFMT+PR+REVIEW%5D%3A)**.

***************************

### What is this change about?

update ginkgo to new major version v2

### What problem it is trying to solve?

"outdated" dependency

### What is the impact if the change is not made?

"outdated" dependency

### CODE REVIEW

**Review by MarcPaquette — APPROVED** [review]
These changes look reasonable to me

**Comment by MarcPaquette** [comment]
@ameowlia are you able to merge these changes in?

**Comment by MarcPaquette** [comment]
Hi @phil9909,
We're seeing some conflicts on this PR. Are you able to resolve these?
Thanks
@MarcPaquette

**Comment by phil9909** [comment]
Looks like someone stole my contribution :disappointed:. Switch to ginkgo v2 was already done in #59 (which was opened over a year after my PR).

**Pull request closed without merging**
