### PR TITLE
Ensure ToBytes is more robust Issue #31

### PR DESCRIPTION
**Pull request by lhendre**
Added a line in the code to ensure the code could handle more robust forms of the data, specifically with more spaces.  Please let me know your thoughts or if you want it to handle more possible inputs

### CODE REVIEW

**Comment by heyjcollins** [comment]
@lhendre - We haven't come upon a need for this change in Cloud Foundry so far. Could you please describe the CFAR problem/use-case that making this change will address?

**Comment by lhendre** [comment]
Hi @heyjcollins this was referenced and accepted in issue 32 but issues dont appear to be viewable anymore.  While ToBytes works in relation to the the format of bytes sizes created by ByteSize and several others, this makes it more useable.  Specifically, many common golang functions, like common.StorageSize(), return the byte size with a space in between them throwing off your function.  This makes the function more robust and able to be used in more places including with common golang functions

**Comment by heyjcollins** [comment]
Thanks @lhendre - makes sense.  Is the absence of support for white space between the value and the units in bytefmt actually preventing you from using bytefmt to add features or complete a bug fix within another repo in CloudFoundry?

**Comment by heyjcollins** [comment]
@lhendre - bumping this thread again with my question:

Is the absence of this change in bytefmt preventing you or your team from using bytefmt to add features or make fixes within another repo within CloudFoundry?

**Comment by aminjam** [comment]
Closing due to inactivity

**Pull request closed without merging**
