### PR TITLE
bytefmt: do not fail ToBytes on 0 value

### LINKED ISSUE #20: support for 0 byte objects in ToBytes

### PR DESCRIPTION
**Pull request by rjeczalik**
Closes #20.

### CODE REVIEW

**Comment by aminjam** [comment]
Thanks for the PR @rjeczalik! We are not sure why originally we had decided to throw an error when a user [passes a `0TB`](https://github.com/cloudfoundry/bytefmt/blob/master/bytes_test.go#L326), since Zero is a valid number. Given that logic is already in place, it seems like we'd breaking backwards compatibility by not returning an error. The only logical scenario where we think it's a good place to have an error is when a CLI user mistakenly enters a `Zero` value and it's caught by the library. 

This PR is short circuiting the `0TB` case and it feels like having different behaviors for the two similar inputs is misleading.

Is there a solution where we can keep this backward compatibility and have a unified behavior for value of Zero?

**Comment by rjeczalik** [comment]
> Is there a solution where we can keep this backward compatibility and have a unified behavior for value of Zero?

Sure. Requires two changes:

- ByteSize(0) should return "0B"
- ToBytes("0B") should return nil error
- ToBytes("0") should return non-nil error

Whatever we so chose, the following code needs to work:

```go
zero := ByteSize(0)
_, err := ToBytes(zero)
```

Otherwise we have an API where one function is expected to produce invalid output out of a valid input.

**Comment by rjeczalik** [comment]
> when a CLI user mistakenly enters

CLI handling is a nice feature, but I'm afraid the check is in the wrong place. What I would do is to:

- add `type Bytes uint64`
- refactor `func ByteSize(bytes uint64) string` -> `func ByteSize(bytes Bytes) string`
- make Bytes type implement [flag.Value](https://golang.org/pkg/flag/#Value) interface
  - make `Bytes.Set(s string) error` return non-nil error when s == "0" (which basically is your use-case - user either provided 0 on the command line or did not set the flag at all)

**Comment by sunjayBhatia** [comment]
We have made the changes described in https://github.com/cloudfoundry/bytefmt/pull/26#issuecomment-521586071 here: https://github.com/cloudfoundry/bytefmt/commit/854d396b647c90b5a45646f9dcc2c9cd08ea8d51

We do not believe we will prioritize the content in https://github.com/cloudfoundry/bytefmt/pull/26#issuecomment-521588000 at this time, feel free to open another issue or PR if you want to add this feature

**Comment by rjeczalik** [comment]
@sunjayBhatia thanks!

**Pull request closed without merging**
